#!/usr/bin/env bash
# ==============================================================================
# scripts/ci/validate-terraform.sh
#
# Validates Terraform across all roots and reusable modules:
# 1. Formatting check via `terraform fmt -check -recursive`.
# 2. Schema validation via `terraform init -backend=false` and `terraform validate`.
# 3. Linter validation via `tflint` (with minimum error severity for blocking).
# ==============================================================================

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "${REPO_ROOT}"

# Source version pins if available
if [[ -f "${REPO_ROOT}/scripts/ci/versions.env" ]]; then
  # shellcheck source=/dev/null
  source "${REPO_ROOT}/scripts/ci/versions.env"
fi

if ! command -v terraform >/dev/null 2>&1; then
  echo "ERROR: terraform CLI is not installed or not in PATH." >&2
  exit 1
fi

echo "==> [Terraform] Checking code formatting..."
terraform fmt -check -recursive

ROOTS=(
  "terraform/live/onprem-pve"
  "terraform/bootstrap/seaweedfs"
)

echo "==> [Terraform] Validating live and bootstrap roots..."
for root in "${ROOTS[@]}"; do
  if [[ -d "${root}" ]]; then
    echo "  -> Initializing and validating root: ${root}"
    terraform -chdir="${root}" init -backend=false
    terraform -chdir="${root}" validate
  fi
done

echo "==> [Terraform] Validating reusable modules..."
if [[ -d "terraform/modules" ]]; then
  for mod in terraform/modules/*; do
    if [[ -d "${mod}" ]]; then
      echo "  -> Initializing and validating module: ${mod}"
      terraform -chdir="${mod}" init -backend=false
      terraform -chdir="${mod}" validate
      # Reusable modules do not track provider locks; remove transient lockfile generated by init
      rm -f "${mod}/.terraform.lock.hcl"
    fi
  done
fi

if command -v tflint >/dev/null 2>&1; then
  echo "==> [Terraform] Running TFLint..."
  tflint --init
  tflint --minimum-failure-severity=error --recursive
else
  echo "WARN: tflint CLI not installed. Skipping TFLint static checks." >&2
fi

echo "==> [Terraform] All Terraform checks passed successfully."
